from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg
import numpy

class Ui_MainWindow(QtGui.QMainWindow):

    ##--> define user interface elements
    def setupUi(self, MainWindow, parent_path):

        # Fonts
        font_headline = QtGui.QFont()
        font_headline.setPointSize(11)
        font_headline.setBold(True)

        font_button = QtGui.QFont()
        font_button.setPointSize(10)
        font_button.setBold(True)

        font_graphs = QtGui.QFont()
        font_graphs.setPixelSize(12)
        font_graphs.setBold(False)

        font_graphs_2 = QtGui.QFont()
        font_graphs_2.setPixelSize(1)
        font_graphs_2.setBold(False)

        font_ee = QtGui.QFont()
        font_ee.setPointSize(8)
        font_ee.setBold(False)

        # Main Window
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1010, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1010, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1010, 720))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setWindowTitle("SuperADAM .h5 data extractor")
        MainWindow.setWindowIcon(QtGui.QIcon(parent_path + "\icon.png"))
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Block: .h5 files
        self.label_h5_files = QtWidgets.QLabel(self.centralwidget)
        self.label_h5_files.setGeometry(QtCore.QRect(15, 5, 200, 20))
        self.label_h5_files.setFont(font_headline)
        self.label_h5_files.setObjectName("label_h5_files")
        self.label_h5_files.setText(".h5 files")

        self.groupBox_data = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_data.setGeometry(QtCore.QRect(10, 10, 280, 667))
        self.groupBox_data.setFont(font_ee)
        self.groupBox_data.setTitle("")
        self.groupBox_data.setObjectName("groupBox_data")
        self.label_data_files = QtWidgets.QLabel(self.groupBox_data)
        self.label_data_files.setGeometry(QtCore.QRect(110, 20, 121, 21))
        self.label_data_files.setFont(font_headline)
        self.label_data_files.setObjectName("label_data_files")
        self.label_data_files.setText("Data files")
        self.tableWidget_Scans = QtWidgets.QTableWidget(self.groupBox_data)
        self.tableWidget_Scans.setFont(font_ee)
        self.tableWidget_Scans.setGeometry(QtCore.QRect(10, 42, 260, 338))
        self.tableWidget_Scans.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Scans.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Scans.setAutoScroll(True)
        self.tableWidget_Scans.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableWidget_Scans.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_Scans.setObjectName("tableWidget_Scans")
        self.tableWidget_Scans.setColumnCount(4)
        self.tableWidget_Scans.setRowCount(0)
        for i in range(0,4):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_Scans.setHorizontalHeaderItem(i, item)
        self.tableWidget_Scans.horizontalHeader().setVisible(True)
        self.tableWidget_Scans.verticalHeader().setVisible(False)
        item = self.tableWidget_Scans.horizontalHeaderItem(0)
        item.setText("Scan")
        # I removed ROI column, so I will remove the column from here when I see its really not necessary to have
        item = self.tableWidget_Scans.horizontalHeaderItem(1)
        item.setText("ROI")
        item = self.tableWidget_Scans.horizontalHeaderItem(2)
        item.setText("DB")
        item = self.tableWidget_Scans.horizontalHeaderItem(3)
        item.setText("Scan_file_full_path")
        self.tableWidget_Scans.setColumnWidth(0, 200)
        self.tableWidget_Scans.setColumnWidth(1, 0)
        self.tableWidget_Scans.setColumnWidth(2, int(self.tableWidget_Scans.width()) - int(self.tableWidget_Scans.columnWidth(0)) - int(self.tableWidget_Scans.columnWidth(1)) - 2)
        self.tableWidget_Scans.setColumnWidth(3, 0)
        self.pushButton_DeleteImportScans = QtWidgets.QPushButton(self.groupBox_data)
        self.pushButton_DeleteImportScans.setGeometry(QtCore.QRect(10, 384, 81, 20))
        self.pushButton_DeleteImportScans.setFont(font_ee)
        self.pushButton_DeleteImportScans.setObjectName("pushButton_DeleteImportScans")
        self.pushButton_DeleteImportScans.setText("Delete scans")
        self.pushButton_importScans = QtWidgets.QPushButton(self.groupBox_data)
        self.pushButton_importScans.setGeometry(QtCore.QRect(189, 384, 81, 20))
        self.pushButton_importScans.setFont(font_ee)
        self.pushButton_importScans.setObjectName("pushButton_importScans")
        self.pushButton_importScans.setText("Import scans")
        self.label_db = QtWidgets.QLabel(self.groupBox_data)
        self.label_db.setGeometry(QtCore.QRect(78, 412, 191, 23))
        self.label_db.setFont(font_headline)
        self.label_db.setObjectName("label_db")
        self.label_db.setText("Direct Beam files")
        self.checkBox_db_arrangement_after = QtWidgets.QCheckBox(self.groupBox_data)
        self.checkBox_db_arrangement_after.setGeometry(QtCore.QRect(10, 432, 210, 20))
        self.checkBox_db_arrangement_after.setFont(font_ee)
        self.checkBox_db_arrangement_after.setObjectName("checkBox_db_arrangement_after")
        self.checkBox_db_arrangement_after.setText("DB's were measured after the scans")
        self.tableWidget_DB = QtWidgets.QTableWidget(self.groupBox_data)
        self.tableWidget_DB.setFont(font_ee)
        self.tableWidget_DB.setGeometry(QtCore.QRect(10, 452, 260, 183))
        self.tableWidget_DB.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_DB.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_DB.setAutoScroll(True)
        self.tableWidget_DB.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableWidget_DB.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_DB.setObjectName("tableWidget_db")
        self.tableWidget_DB.setColumnCount(2)
        self.tableWidget_DB.setRowCount(0)
        for i in range(0, 2):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_DB.setHorizontalHeaderItem(i, item)
        self.tableWidget_DB.horizontalHeader().setVisible(False)
        self.tableWidget_DB.verticalHeader().setVisible(False)
        item = self.tableWidget_DB.horizontalHeaderItem(0)
        item.setText("Scan")
        item = self.tableWidget_DB.horizontalHeaderItem(1)
        item.setText("Path")
        self.tableWidget_DB.setColumnWidth(0, self.tableWidget_DB.width())
        self.tableWidget_DB.setColumnWidth(1, 0)
        self.tableWidget_DB.setSortingEnabled(True)
        self.pushButton_DeleteImportDB = QtWidgets.QPushButton(self.groupBox_data)
        self.pushButton_DeleteImportDB.setGeometry(QtCore.QRect(10, 639, 81, 20))
        self.pushButton_DeleteImportDB.setFont(font_ee)
        self.pushButton_DeleteImportDB.setObjectName("pushButton_DeleteImportDB")
        self.pushButton_DeleteImportDB.setText("Delete DB")
        self.pushButton_ImportDB = QtWidgets.QPushButton(self.groupBox_data)
        self.pushButton_ImportDB.setGeometry(QtCore.QRect(189, 639, 81, 20))
        self.pushButton_ImportDB.setFont(font_ee)
        self.pushButton_ImportDB.setObjectName("pushButton_ImportDB")
        self.pushButton_ImportDB.setText("Import DB")

        # Block: Sample
        self.label_sample = QtWidgets.QLabel(self.centralwidget)
        self.label_sample.setGeometry(QtCore.QRect(305, 5, 200, 20))
        self.label_sample.setFont(font_headline)
        self.label_sample.setObjectName("label_sample")
        self.label_sample.setText("Sample")
        self.groupBox_sample_len = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_sample_len.setGeometry(QtCore.QRect(300, 10, 282, 47))
        self.groupBox_sample_len.setFont(font_ee)
        self.groupBox_sample_len.setTitle("")
        self.groupBox_sample_len.setObjectName("groupBox_sample_len")
        self.label_sample_len = QtWidgets.QLabel(self.groupBox_sample_len)
        self.label_sample_len.setGeometry(QtCore.QRect(10, 24, 131, 16))
        self.label_sample_len.setFont(font_ee)
        self.label_sample_len.setObjectName("label_sample_len")
        self.label_sample_len.setText("Sample length (mm)")
        self.lineEdit_SampleLength = QtWidgets.QLineEdit(self.groupBox_sample_len)
        self.lineEdit_SampleLength.setGeometry(QtCore.QRect(192, 22, 83, 21))
        self.lineEdit_SampleLength.setObjectName("lineEdit_SampleLength")
        self.lineEdit_SampleLength.setText("50")

        # Block: Reductions and Instrument settings
        self.label_reductions = QtWidgets.QLabel(self.centralwidget)
        self.label_reductions.setGeometry(QtCore.QRect(305, 65, 200, 16))
        self.label_reductions.setFont(font_headline)
        self.label_reductions.setObjectName("label_reductions")
        self.label_reductions.setText("Reductions")
        self.tabWidget_red_instr_exp = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_red_instr_exp.setGeometry(QtCore.QRect(300, 87, 281, 226))
        self.tabWidget_red_instr_exp.setFont(font_ee)
        self.tabWidget_red_instr_exp.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_red_instr_exp.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_red_instr_exp.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_red_instr_exp.setObjectName("tabWidget_red_instr_exp")

        # Tab: Reductions
        self.tab_reduct = QtWidgets.QWidget()
        self.tab_reduct.setObjectName("tab_reduct")
        self.checkBox_DevideByMon = QtWidgets.QCheckBox(self.tab_reduct)
        self.checkBox_DevideByMon.setGeometry(QtCore.QRect(10, 10, 131, 18))
        self.checkBox_DevideByMon.setFont(font_ee)
        self.checkBox_DevideByMon.setObjectName("checkBox_DevideByMon")
        self.checkBox_DevideByMon.setText("Devide by monitor")
        self.checkBox_NormDB = QtWidgets.QCheckBox(self.tab_reduct)
        self.checkBox_NormDB.setGeometry(QtCore.QRect(10, 35, 181, 18))
        self.checkBox_NormDB.setFont(font_ee)
        self.checkBox_NormDB.setObjectName("checkBox_NormDB")
        self.checkBox_NormDB.setText("Normalise by direct beam")
        self.checkBox_DBatten = QtWidgets.QCheckBox(self.tab_reduct)
        self.checkBox_DBatten.setGeometry(QtCore.QRect(10, 60, 161, 18))
        self.checkBox_DBatten.setFont(font_ee)
        self.checkBox_DBatten.setChecked(True)
        self.checkBox_DBatten.setObjectName("checkBox_DBatten")
        self.checkBox_DBatten.setText("Direct beam attenuator")
        self.lineEdit_AttenCorrFactor = QtWidgets.QLineEdit(self.tab_reduct)
        self.lineEdit_AttenCorrFactor.setGeometry(QtCore.QRect(30, 85, 221, 20))
        self.lineEdit_AttenCorrFactor.setFont(font_ee)
        self.lineEdit_AttenCorrFactor.setText("")
        self.lineEdit_AttenCorrFactor.setObjectName("lineEdit_AttenCorrFactor")
        self.lineEdit_AttenCorrFactor.setPlaceholderText("Attenuator correction [default 10.4]")
        self.checkBox_SubtrBKG = QtWidgets.QCheckBox(self.tab_reduct)
        self.checkBox_SubtrBKG.setGeometry(QtCore.QRect(10, 115, 231, 18))
        self.checkBox_SubtrBKG.setFont(font_ee)
        self.checkBox_SubtrBKG.setObjectName("checkBox_SubtrBKG")
        self.checkBox_SubtrBKG.setText("Subtract background (using 1 ROI)")
        self.lineEdit_SkipSubtrBKG = QtWidgets.QLineEdit(self.tab_reduct)
        self.lineEdit_SkipSubtrBKG.setGeometry(QtCore.QRect(30, 140, 221, 20))
        self.lineEdit_SkipSubtrBKG.setFont(font_ee)
        self.lineEdit_SkipSubtrBKG.setObjectName("lineEdit_SkipSubtrBKG")
        self.lineEdit_SkipSubtrBKG.setPlaceholderText("Skip background corr. at Qz < [default 0]")
        self.checkBox_OverillCorr = QtWidgets.QCheckBox(self.tab_reduct)
        self.checkBox_OverillCorr.setGeometry(QtCore.QRect(10, 170, 181, 18))
        self.checkBox_OverillCorr.setFont(font_ee)
        self.checkBox_OverillCorr.setObjectName("checkBox_OverillCorr")
        self.checkBox_OverillCorr.setText("Overillumination correction")
        self.tabWidget_red_instr_exp.addTab(self.tab_reduct, "")
        self.tabWidget_red_instr_exp.setTabText(0, "Reductions")

        # Tab: Instrument settings
        self.tab_instr = QtWidgets.QWidget()
        self.tab_instr.setObjectName("tab_instr")
        self.label_wavelength = QtWidgets.QLabel(self.tab_instr)
        self.label_wavelength.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label_wavelength.setFont(font_ee)
        self.label_wavelength.setObjectName("label_wavelength")
        self.label_wavelength.setText("Wavelength (A)")
        self.lineEdit_wavelength = QtWidgets.QLineEdit(self.tab_instr)
        self.lineEdit_wavelength.setGeometry(QtCore.QRect(220, 10, 41, 20))
        self.lineEdit_wavelength.setFont(font_ee)
        self.lineEdit_wavelength.setObjectName("lineEdit_wavelength")
        self.lineEdit_wavelength.setText("5.2")
        self.label_wavel_resol = QtWidgets.QLabel(self.tab_instr)
        self.label_wavel_resol.setGeometry(QtCore.QRect(10, 35, 271, 16))
        self.label_wavel_resol.setFont(font_ee)
        self.label_wavel_resol.setObjectName("label_wavel_resol")
        self.label_wavel_resol.setText("Wavelength resolution (d_lambda/lambda)")
        self.lineEdit_wavel_resol = QtWidgets.QLineEdit(self.tab_instr)
        self.lineEdit_wavel_resol.setGeometry(QtCore.QRect(220, 35, 41, 20))
        self.lineEdit_wavel_resol.setFont(font_ee)
        self.lineEdit_wavel_resol.setObjectName("lineEdit_wavel_resol")
        self.lineEdit_wavel_resol.setText("0.007")
        self.label_s1_sample_dist = QtWidgets.QLabel(self.tab_instr)
        self.label_s1_sample_dist.setGeometry(QtCore.QRect(10, 60, 241, 16))
        self.label_s1_sample_dist.setFont(font_ee)
        self.label_s1_sample_dist.setObjectName("label_s1_sample_dist")
        self.label_s1_sample_dist.setText("Mono_slit to Samplle distance (mm)")
        self.lineEdit_s1_sample_dist = QtWidgets.QLineEdit(self.tab_instr)
        self.lineEdit_s1_sample_dist.setGeometry(QtCore.QRect(220, 60, 41, 20))
        self.lineEdit_s1_sample_dist.setFont(font_ee)
        self.lineEdit_s1_sample_dist.setObjectName("lineEdit_s1_sample_dist")
        self.lineEdit_s1_sample_dist.setText("2350")
        self.label_s2_sample_dist = QtWidgets.QLabel(self.tab_instr)
        self.label_s2_sample_dist.setGeometry(QtCore.QRect(10, 85, 241, 16))
        self.label_s2_sample_dist.setFont(font_ee)
        self.label_s2_sample_dist.setObjectName("label_s2_sample_dist")
        self.label_s2_sample_dist.setText("Sample_slit to Sample distance (mm)")
        self.lineEdit_s2_sample_dist = QtWidgets.QLineEdit(self.tab_instr)
        self.lineEdit_s2_sample_dist.setGeometry(QtCore.QRect(220, 85, 41, 20))
        self.lineEdit_s2_sample_dist.setFont(font_ee)
        self.lineEdit_s2_sample_dist.setObjectName("lineEdit_s2_sample_dist")
        self.lineEdit_s2_sample_dist.setText("195")
        self.label_sample_det_dist = QtWidgets.QLabel(self.tab_instr)
        self.label_sample_det_dist.setGeometry(QtCore.QRect(10, 110, 241, 16))
        self.label_sample_det_dist.setFont(font_ee)
        self.label_sample_det_dist.setObjectName("label_sample_det_dist")
        self.label_sample_det_dist.setText("Samplle to Detector distance (mm)")
        self.lineEdit_sample_det_dist = QtWidgets.QLineEdit(self.tab_instr)
        self.lineEdit_sample_det_dist.setGeometry(QtCore.QRect(220, 110, 41, 20))
        self.lineEdit_sample_det_dist.setFont(font_ee)
        self.lineEdit_sample_det_dist.setObjectName("lineEdit_sample_det_dist")
        self.lineEdit_sample_det_dist.setText("2500")
        '''
        self.label_th_offset = QtWidgets.QLabel(self.tab_instr)
        self.label_th_offset.setGeometry(QtCore.QRect(10, 150, 241, 16))
        self.label_th_offset.setFont(font_ee)
        self.label_th_offset.setObjectName("label_th_offset")
        self.label_th_offset.setText("th offset (deg) (SFM only)")
        self.lineEdit_th_offset = QtWidgets.QLineEdit(self.tab_instr)
        self.lineEdit_th_offset.setGeometry(QtCore.QRect(220, 150, 41, 20))
        self.lineEdit_th_offset.setFont(font_ee)
        self.lineEdit_th_offset.setObjectName("lineEdit_sample_det_dist")
        self.lineEdit_th_offset.setText("0")
        '''
        self.label_full_scan_offset = QtWidgets.QLabel(self.tab_instr)
        self.label_full_scan_offset.setGeometry(QtCore.QRect(10, 175, 241, 16))
        self.label_full_scan_offset.setFont(font_ee)
        self.label_full_scan_offset.setObjectName("label_full_scan_offset")
        self.label_full_scan_offset.setText("Full scan offset (th - deg) (SFM only)")
        self.lineEdit_full_scan_offset = QtWidgets.QLineEdit(self.tab_instr)
        self.lineEdit_full_scan_offset.setGeometry(QtCore.QRect(220, 175, 41, 20))
        self.lineEdit_full_scan_offset.setFont(font_ee)
        self.lineEdit_full_scan_offset.setObjectName("lineEdit_full_scan_offset")
        self.lineEdit_full_scan_offset.setText("0")
        self.tabWidget_red_instr_exp.addTab(self.tab_instr, "")
        self.tabWidget_red_instr_exp.setTabText(1, "Instrument settings")

        # Tab: Export options
        self.tab_export_options = QtWidgets.QWidget()
        self.tab_export_options.setObjectName("tab_export_options")
        self.checkBox_add_resolution_column = QtWidgets.QCheckBox(self.tab_export_options)
        self.checkBox_add_resolution_column.setGeometry(QtCore.QRect(10, 10, 250, 18))
        self.checkBox_add_resolution_column.setFont(font_ee)
        self.checkBox_add_resolution_column.setChecked(True)
        self.checkBox_add_resolution_column.setObjectName("checkBox_add_resolution_column")
        self.checkBox_add_resolution_column.setText("Include ang. resolution column in the output file")
        self.checkBox_resol_sared = QtWidgets.QCheckBox(self.tab_export_options)
        self.checkBox_resol_sared.setGeometry(QtCore.QRect(30, 35, 250, 18))
        self.checkBox_resol_sared.setFont(font_ee)
        self.checkBox_resol_sared.setChecked(True)
        self.checkBox_resol_sared.setObjectName("checkBox_resol_sared")
        self.checkBox_resol_sared.setText("Calculate ang. resolution in 'Sared' way")

        self.checkBox_remove_zeros = QtWidgets.QCheckBox(self.tab_export_options)
        self.checkBox_remove_zeros.setGeometry(QtCore.QRect(10, 60, 250, 18))
        self.checkBox_remove_zeros.setFont(font_ee)
        self.checkBox_remove_zeros.setChecked(False)
        self.checkBox_remove_zeros.setObjectName("checkBox_remove_zeros")
        self.checkBox_remove_zeros.setText("Remove zeros from reduced files")

        self.tabWidget_red_instr_exp.addTab(self.tab_export_options, "")
        self.tabWidget_red_instr_exp.setTabText(2, "Export")

        # Block: Save reduced files at
        self.label_save_at = QtWidgets.QLabel(self.centralwidget)
        self.label_save_at.setGeometry(QtCore.QRect(305, 320, 200, 20))
        self.label_save_at.setFont(font_headline)
        self.label_save_at.setObjectName("label_save_at")
        self.label_save_at.setText("Save reduced files at")
        self.groupBox_save_at = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_save_at.setGeometry(QtCore.QRect(300, 325, 282, 48))
        self.groupBox_save_at.setFont(font_ee)
        self.groupBox_save_at.setTitle("")
        self.groupBox_save_at.setObjectName("groupBox_save_at")
        self.lineEdit_saveAt = QtWidgets.QLineEdit(self.groupBox_save_at)
        self.lineEdit_saveAt.setGeometry(QtCore.QRect(10, 22, 225, 22))
        self.lineEdit_saveAt.setFont(font_ee)
        self.lineEdit_saveAt.setObjectName("lineEdit_saveAt")
        self.lineEdit_saveAt.setPlaceholderText(parent_path)
        self.toolButton_save_at = QtWidgets.QToolButton(self.groupBox_save_at)
        self.toolButton_save_at.setGeometry(QtCore.QRect(248, 22, 27, 22))
        self.toolButton_save_at.setObjectName("toolButton_save_at")
        self.toolButton_save_at.setText("...")

        # Button: Clear
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(300, 380, 88, 30))
        self.pushButton_clear.setFont(font_button)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_clear.setText("Clear all")

        # Button: Reduce all
        self.pushButton_start_all = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start_all.setGeometry(QtCore.QRect(494, 380, 88, 30))
        self.pushButton_start_all.setFont(font_button)
        self.pushButton_start_all.setObjectName("pushButton_start_all")
        self.pushButton_start_all.setText("Reduce all")

        # Errors
        self.label_sample_len_missing = QtWidgets.QLabel(self.centralwidget)
        self.label_sample_len_missing.setGeometry(QtCore.QRect(360, 420, 181, 31))
        self.label_sample_len_missing.setFont(font_button)
        self.label_sample_len_missing.setObjectName("label_sample_len_missing")
        self.label_sample_len_missing.setVisible(False)
        self.label_sample_len_missing.setText("Sample length is missing")
        self.label_sample_len_missing.setStyleSheet("color:rgb(255,0,0)")
        self.label_DB_missing = QtWidgets.QLabel(self.centralwidget)
        self.label_DB_missing.setGeometry(QtCore.QRect(355, 450, 181, 31))
        self.label_DB_missing.setFont(font_button)
        self.label_DB_missing.setObjectName("label_DB_missing")
        self.label_DB_missing.setVisible(False)
        self.label_DB_missing.setText("Direct beam file is missing")
        self.label_DB_missing.setStyleSheet("color:rgb(255,0,0)")
        self.label_wrong_roi_input = QtWidgets.QLabel(self.centralwidget)
        self.label_wrong_roi_input.setGeometry(QtCore.QRect(360, 435, 181, 31))
        self.label_wrong_roi_input.setFont(font_button)
        self.label_wrong_roi_input.setObjectName("label_wrong_roi_input")
        self.label_wrong_roi_input.setVisible(False)
        self.label_wrong_roi_input.setText("Recheck your ROI input")
        self.label_wrong_roi_input.setStyleSheet("color:rgb(255,0,0)")

        # Block: Recheck following files in SFM
        self.label_recheck_with_sared = QtWidgets.QLabel(self.centralwidget)
        self.label_recheck_with_sared.setGeometry(QtCore.QRect(305, 490, 250, 20))
        self.label_recheck_with_sared.setFont(font_headline)
        self.label_recheck_with_sared.setObjectName("label_recheck_with_sared")
        self.label_recheck_with_sared.setText("Recheck following files in SFM")
        self.groupBox_recheck_files = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_recheck_files.setGeometry(QtCore.QRect(300, 497, 282, 180))
        self.groupBox_recheck_files.setFont(font_ee)
        self.groupBox_recheck_files.setTitle("")
        self.groupBox_recheck_files.setObjectName("groupBox_recheck_files")
        self.listWidget_filesToCheck = QtWidgets.QListWidget(self.groupBox_recheck_files)
        self.listWidget_filesToCheck.setGeometry(QtCore.QRect(10, 27, 262, 145))
        self.listWidget_filesToCheck.setObjectName("listWidget_filesToCheck")

        # Block: Single File Mode
        self.label_SFM = QtWidgets.QLabel(self.centralwidget)
        self.label_SFM.setGeometry(QtCore.QRect(596, 5, 200, 20))
        self.label_SFM.setFont(font_headline)
        self.label_SFM.setObjectName("label_SFM")
        self.label_SFM.setText("Single File Mode (SFM)")
        self.groupBox_load_scan = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_load_scan.setGeometry(QtCore.QRect(591, 10, 302, 48))
        self.groupBox_load_scan.setTitle("")
        self.groupBox_load_scan.setObjectName("groupBox_load_scan")
        self.label_scan = QtWidgets.QLabel(self.groupBox_load_scan)
        self.label_scan.setGeometry(QtCore.QRect(10, 23, 47, 20))
        self.label_scan.setObjectName("label_scan")
        self.label_scan.setText("Scan")
        self.label_scan.setFont(font_ee)
        self.comboBox_scan = QtWidgets.QComboBox(self.groupBox_load_scan)
        self.comboBox_scan.setGeometry(QtCore.QRect(40, 23, 255, 20))
        self.comboBox_scan.setObjectName("comboBox_scan")
        self.comboBox_scan.setFont(font_ee)
        pg.setConfigOption('background', (255, 255, 255))
        pg.setConfigOption('foreground', 'k')

        # Button: Reduce SFM
        self.pushButton_start_sfm = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start_sfm.setGeometry(QtCore.QRect(900, 28, 100, 30))
        self.pushButton_start_sfm.setFont(font_button)
        self.pushButton_start_sfm.setObjectName("pushButton_start_sfm")
        self.pushButton_start_sfm.setText("Reduce SFM")

        # Block: Detector Images and Reflectivity preview
        self.tabWidget_SFM = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_SFM.setGeometry(QtCore.QRect(592, 65, 408, 613))
        self.tabWidget_SFM.setFont(font_ee)
        self.tabWidget_SFM.setObjectName("tabWidget_SFM")

        # Tab: Detector images
        linedit_size_X = 30
        linedit_size_Y = 18
        self.tab_det_images = QtWidgets.QWidget()
        self.tab_det_images.setObjectName("tab_det_images")
        self.graphicsView_det_integr = pg.PlotWidget(self.tab_det_images)
        self.graphicsView_det_integr.setGeometry(QtCore.QRect(0, 430, 407, 90))
        self.graphicsView_det_integr.setObjectName("graphicsView_det_integr")
        self.graphicsView_det_integr.hideAxis("left")
        self.graphicsView_det_integr.setMouseEnabled(y=False)
        self.graphicsView_det_images = pg.ImageView(self.tab_det_images)
        self.graphicsView_det_images.setGeometry(QtCore.QRect(0, 30, 407, 490))
        self.graphicsView_det_images.setObjectName("graphicsView_det_images")
        self.graphicsView_det_images.ui.histogram.hide()
        self.graphicsView_det_images.ui.menuBtn.hide()
        self.graphicsView_det_images.ui.roiBtn.hide()
        self.label_point_number = QtWidgets.QLabel(self.tab_det_images)
        self.label_point_number.setFont(font_ee)
        self.label_point_number.setGeometry(QtCore.QRect(10, 8, 70, 16))
        self.label_point_number.setObjectName("label_point_number")
        self.label_point_number.setText("Point number")
        self.comboBox_point_number = QtWidgets.QComboBox(self.tab_det_images)
        self.comboBox_point_number.setFont(font_ee)
        self.comboBox_point_number.setGeometry(QtCore.QRect(80, 7, 55, 20))
        self.comboBox_point_number.setObjectName("comboBox_point_number")
        self.label_polarisation = QtWidgets.QLabel(self.tab_det_images)
        self.label_polarisation.setFont(font_ee)
        self.label_polarisation.setGeometry(QtCore.QRect(155, 8, 60, 16))
        self.label_polarisation.setObjectName("label_polarisation")
        self.label_polarisation.setText("Polarisation")
        self.comboBox_polarisation = QtWidgets.QComboBox(self.tab_det_images)
        self.comboBox_polarisation.setFont(font_ee)
        self.comboBox_polarisation.setGeometry(QtCore.QRect(215, 7, 40, 20))
        self.comboBox_polarisation.setObjectName("comboBox_polarisation")
        self.label_color_scheme = QtWidgets.QLabel(self.tab_det_images)
        self.label_color_scheme.setFont(font_ee)
        self.label_color_scheme.setGeometry(QtCore.QRect(268, 8, 60, 16))
        self.label_color_scheme.setObjectName("label_color_scheme")
        self.label_color_scheme.setText("Colors")
        self.comboBox_colors_cheme = QtWidgets.QComboBox(self.tab_det_images)
        self.comboBox_colors_cheme.setFont(font_ee)
        self.comboBox_colors_cheme.setGeometry(QtCore.QRect(305, 7, 90, 20))
        self.comboBox_colors_cheme.setObjectName("comboBox_colors_cheme")
        self.label_slits = QtWidgets.QLabel(self.tab_det_images)
        self.label_slits.setFont(font_ee)
        self.label_slits.setGeometry(QtCore.QRect(10, 525, 51, 16))
        self.label_slits.setObjectName("label_slits")
        self.label_slits.setText("Slits (mm):")
        self.label_slit_s1hg = QtWidgets.QLabel(self.tab_det_images)
        self.label_slit_s1hg.setFont(font_ee)
        self.label_slit_s1hg.setGeometry(QtCore.QRect(65, 525, 41, 16))
        self.label_slit_s1hg.setObjectName("label_slit_s1hg")
        self.label_slit_s1hg.setText("s1hg")
        self.lineEdit_slits_s1hg = QtWidgets.QLineEdit(self.tab_det_images)
        self.lineEdit_slits_s1hg.setFont(font_ee)
        self.lineEdit_slits_s1hg.setGeometry(QtCore.QRect(100, 525, linedit_size_X, linedit_size_Y))
        self.lineEdit_slits_s1hg.setObjectName("lineEdit_slits_s1hg")
        self.lineEdit_slits_s1hg.setEnabled(False)
        self.lineEdit_slits_s1hg.setStyleSheet("color:rgb(0,0,0)")
        self.label_slit_s2hg = QtWidgets.QLabel(self.tab_det_images)
        self.label_slit_s2hg.setFont(font_ee)
        self.label_slit_s2hg.setGeometry(QtCore.QRect(140, 525, 47, 16))
        self.label_slit_s2hg.setObjectName("label_slit_s2hg")
        self.label_slit_s2hg.setText("s2hg")
        self.lineEdit_slits_s2hg = QtWidgets.QLineEdit(self.tab_det_images)
        self.lineEdit_slits_s2hg.setFont(font_ee)
        self.lineEdit_slits_s2hg.setGeometry(QtCore.QRect(165, 525, linedit_size_X, linedit_size_Y))
        self.lineEdit_slits_s2hg.setObjectName("lineEdit_slits_s2hg")
        self.lineEdit_slits_s2hg.setEnabled(False)
        self.lineEdit_slits_s2hg.setStyleSheet("color:rgb(0,0,0)")
        self.label_time = QtWidgets.QLabel(self.tab_det_images)
        self.label_time.setFont(font_ee)
        self.label_time.setGeometry(QtCore.QRect(220, 525, 71, 16))
        self.label_time.setObjectName("label_time")
        self.label_time.setText("Time (s):")
        self.lineEdit_time = QtWidgets.QLineEdit(self.tab_det_images)
        self.lineEdit_time.setFont(font_ee)
        self.lineEdit_time.setGeometry(QtCore.QRect(300, 525, linedit_size_X, linedit_size_Y))
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.lineEdit_time.setEnabled(False)
        self.lineEdit_time.setStyleSheet("color:rgb(0,0,0)")
        self.pushButton_det_int_show = QtWidgets.QPushButton(self.tab_det_images)
        self.pushButton_det_int_show.setGeometry(QtCore.QRect(365, 525, 30, 18))
        self.pushButton_det_int_show.setFont(font_headline)
        self.pushButton_det_int_show.setObjectName("pushButton_det_int_show")
        self.pushButton_det_int_show.setText("+")
        self.pushButton_det_int_show.setStyleSheet("color:rgb(255,0,0)")
        self.label_ROI = QtWidgets.QLabel(self.tab_det_images)
        self.label_ROI.setFont(font_ee)
        self.label_ROI.setGeometry(QtCore.QRect(10, 545, 31, 16))
        self.label_ROI.setObjectName("label_ROI")
        self.label_ROI.setText("ROI:  ")
        self.label_ROI_x_left = QtWidgets.QLabel(self.tab_det_images)
        self.label_ROI_x_left.setFont(font_ee)
        self.label_ROI_x_left.setGeometry(QtCore.QRect(65, 545, 51, 16))
        self.label_ROI_x_left.setObjectName("label_ROI_x_left")
        self.label_ROI_x_left.setText("left")
        self.lineEdit_ROI_x_left = QtWidgets.QLineEdit(self.tab_det_images)
        self.lineEdit_ROI_x_left.setFont(font_ee)
        self.lineEdit_ROI_x_left.setGeometry(QtCore.QRect(100, 545, linedit_size_X, linedit_size_Y))
        self.lineEdit_ROI_x_left.setObjectName("lineEdit_ROI_x_left")
        self.label_ROI_x_right = QtWidgets.QLabel(self.tab_det_images)
        self.label_ROI_x_right.setFont(font_ee)
        self.label_ROI_x_right.setGeometry(QtCore.QRect(140, 545, 51, 16))
        self.label_ROI_x_right.setObjectName("label_ROI_x_right")
        self.label_ROI_x_right.setText("right")
        self.lineEdit_ROI_x_right = QtWidgets.QLineEdit(self.tab_det_images)
        self.lineEdit_ROI_x_right.setFont(font_ee)
        self.lineEdit_ROI_x_right.setGeometry(QtCore.QRect(165, 545, linedit_size_X, linedit_size_Y))
        self.lineEdit_ROI_x_right.setObjectName("lineEdit_ROI_x_right")
        self.label_ROI_y_bottom = QtWidgets.QLabel(self.tab_det_images)
        self.label_ROI_y_bottom.setFont(font_ee)
        self.label_ROI_y_bottom.setGeometry(QtCore.QRect(65, 565, 51, 16))
        self.label_ROI_y_bottom.setObjectName("label_ROI_y_bottom")
        self.label_ROI_y_bottom.setText("bottom")
        self.lineEdit_ROI_y_bottom = QtWidgets.QLineEdit(self.tab_det_images)
        self.lineEdit_ROI_y_bottom.setFont(font_ee)
        self.lineEdit_ROI_y_bottom.setGeometry(QtCore.QRect(100, 565, linedit_size_X, linedit_size_Y))
        self.lineEdit_ROI_y_bottom.setObjectName("lineEdit_ROI_y_bottom")
        self.label_ROI_y_top = QtWidgets.QLabel(self.tab_det_images)
        self.label_ROI_y_top.setFont(font_ee)
        self.label_ROI_y_top.setGeometry(QtCore.QRect(140, 565, 51, 16))
        self.label_ROI_y_top.setObjectName("label_ROI_y_top")
        self.label_ROI_y_top.setText("top")
        self.lineEdit_ROI_y_top = QtWidgets.QLineEdit(self.tab_det_images)
        self.lineEdit_ROI_y_top.setFont(font_ee)
        self.lineEdit_ROI_y_top.setGeometry(QtCore.QRect(165, 565, linedit_size_X, linedit_size_Y))
        self.lineEdit_ROI_y_top.setObjectName("lineEdit_ROI_y_top")

        self.label_ROI_BKG = QtWidgets.QLabel(self.tab_det_images)
        self.label_ROI_BKG.setFont(font_ee)
        self.label_ROI_BKG.setGeometry(QtCore.QRect(220, 545, 47, 16))
        self.label_ROI_BKG.setObjectName("label_ROI_BKG")
        self.label_ROI_BKG.setText("ROI BKG:")
        self.label_ROI_BKG_x_left = QtWidgets.QLabel(self.tab_det_images)
        self.label_ROI_BKG_x_left.setFont(font_ee)
        self.label_ROI_BKG_x_left.setGeometry(QtCore.QRect(265, 545, 51, 16))
        self.label_ROI_BKG_x_left.setObjectName("label_ROI_BKG_x_left")
        self.label_ROI_BKG_x_left.setText("left")
        self.lineEdit_ROI_BKG_x_left = QtWidgets.QLineEdit(self.tab_det_images)
        self.lineEdit_ROI_BKG_x_left.setFont(font_ee)
        self.lineEdit_ROI_BKG_x_left.setGeometry(QtCore.QRect(300, 545, linedit_size_X, linedit_size_Y))
        self.lineEdit_ROI_BKG_x_left.setObjectName("lineEdit_ROI_BKG_x_left")
        self.lineEdit_ROI_BKG_x_left.setEnabled(False)
        self.lineEdit_ROI_BKG_x_left.setStyleSheet("color:rgb(0,0,0)")
        self.label_ROI_BKG_x_right = QtWidgets.QLabel(self.tab_det_images)
        self.label_ROI_BKG_x_right.setFont(font_ee)
        self.label_ROI_BKG_x_right.setGeometry(QtCore.QRect(340, 545, 51, 16))
        self.label_ROI_BKG_x_right.setObjectName("label_ROI_BKG_x_right")
        self.label_ROI_BKG_x_right.setText("right")
        self.lineEdit_ROI_BKG_x_right = QtWidgets.QLineEdit(self.tab_det_images)
        self.lineEdit_ROI_BKG_x_right.setFont(font_ee)
        self.lineEdit_ROI_BKG_x_right.setGeometry(QtCore.QRect(365, 545, linedit_size_X, linedit_size_Y))
        self.lineEdit_ROI_BKG_x_right.setObjectName("lineEdit_ROI_BKG_x_right")
        self.label_ROI_BKG_y_bottom = QtWidgets.QLabel(self.tab_det_images)
        self.label_ROI_BKG_y_bottom.setFont(font_ee)
        self.label_ROI_BKG_y_bottom.setGeometry(QtCore.QRect(265, 565, 51, 16))
        self.label_ROI_BKG_y_bottom.setObjectName("label_ROI_BKG_y_bottom")
        self.label_ROI_BKG_y_bottom.setText("bottom")
        self.lineEdit_ROI_BKG_y_bottom = QtWidgets.QLineEdit(self.tab_det_images)
        self.lineEdit_ROI_BKG_y_bottom.setFont(font_ee)
        self.lineEdit_ROI_BKG_y_bottom.setGeometry(QtCore.QRect(300, 565, linedit_size_X, linedit_size_Y))
        self.lineEdit_ROI_BKG_y_bottom.setObjectName("lineEdit_ROI_BKG_y_bottom")
        self.lineEdit_ROI_BKG_y_bottom.setEnabled(False)
        self.lineEdit_ROI_BKG_y_bottom.setStyleSheet("color:rgb(0,0,0)")
        self.label_ROI_BKG_y_top = QtWidgets.QLabel(self.tab_det_images)
        self.label_ROI_BKG_y_top.setFont(font_ee)
        self.label_ROI_BKG_y_top.setGeometry(QtCore.QRect(340, 565, 51, 16))
        self.label_ROI_BKG_y_top.setObjectName("label_ROI_BKG_y_top")
        self.label_ROI_BKG_y_top.setText("top")
        self.lineEdit_ROI_BKG_y_top = QtWidgets.QLineEdit(self.tab_det_images)
        self.lineEdit_ROI_BKG_y_top.setFont(font_ee)
        self.lineEdit_ROI_BKG_y_top.setGeometry(QtCore.QRect(365, 565, linedit_size_X, linedit_size_Y))
        self.lineEdit_ROI_BKG_y_top.setObjectName("lineEdit_ROI_BKG_y_top")
        self.lineEdit_ROI_BKG_y_top.setEnabled(False)
        self.lineEdit_ROI_BKG_y_top.setStyleSheet("color:rgb(0,0,0)")

        self.tabWidget_SFM.addTab(self.tab_det_images, "")
        self.tabWidget_SFM.setTabText(self.tabWidget_SFM.indexOf(self.tab_det_images), "Detector Images")

        # Tab: Reflectivity preview
        self.tab_refl_preview = QtWidgets.QWidget()
        self.tab_refl_preview.setObjectName("tab_refl_preview")
        self.graphicsView_refl_profile = pg.PlotWidget(self.tab_refl_preview)
        self.graphicsView_refl_profile.setGeometry(QtCore.QRect(0, 20, 407, 540))
        self.graphicsView_refl_profile.setObjectName("graphicsView_refl_profile")
        self.graphicsView_refl_profile.getAxis("bottom").tickFont = font_graphs
        self.graphicsView_refl_profile.getAxis("bottom").setStyle(tickTextOffset=10)
        self.graphicsView_refl_profile.getAxis("left").tickFont = font_graphs
        self.graphicsView_refl_profile.getAxis("left").setStyle(tickTextOffset=10)
        self.graphicsView_refl_profile.showAxis("top")
        self.graphicsView_refl_profile.getAxis("top").tickFont = font_graphs_2
        self.graphicsView_refl_profile.getAxis("top").setStyle(tickTextOffset=-2)
        self.graphicsView_refl_profile.showAxis("right")
        self.graphicsView_refl_profile.getAxis("right").tickFont = font_graphs_2
        self.graphicsView_refl_profile.getAxis("right").setStyle(tickTextOffset=-2)
        self.checkBox_show_overillumination = QtWidgets.QCheckBox(self.tab_refl_preview)
        self.checkBox_show_overillumination.setFont(font_ee)
        self.checkBox_show_overillumination.setGeometry(QtCore.QRect(10, 7, 150, 18))
        self.checkBox_show_overillumination.setObjectName("checkBox_show_overillumination")
        self.checkBox_show_overillumination.setText("Show Overillumination")
        self.comboBox_plot_axis = QtWidgets.QComboBox(self.tab_refl_preview)
        self.comboBox_plot_axis.setFont(font_ee)
        self.comboBox_plot_axis.setGeometry(QtCore.QRect(210, 7, 185, 20))
        self.comboBox_plot_axis.setObjectName("comboBox_plot_axis")
        self.checkBox_incl_errorbars = QtWidgets.QCheckBox(self.tab_refl_preview)
        self.checkBox_incl_errorbars.setFont(font_ee)
        self.checkBox_incl_errorbars.setGeometry(QtCore.QRect(10, 565, 111, 18))
        self.checkBox_incl_errorbars.setObjectName("checkBox_incl_errorbars")
        self.checkBox_incl_errorbars.setText("Include Error Bars")
        self.label_skip_first_points = QtWidgets.QLabel(self.tab_refl_preview)
        self.label_skip_first_points.setFont(font_ee)
        self.label_skip_first_points.setGeometry(QtCore.QRect(187, 565, 100, 16))
        self.label_skip_first_points.setObjectName("label_skip_first_points")
        self.label_skip_first_points.setText("Points to skip:  left")
        self.lineEdit_skip_first_points = QtWidgets.QLineEdit(self.tab_refl_preview)
        self.lineEdit_skip_first_points.setFont(font_ee)
        self.lineEdit_skip_first_points.setGeometry(QtCore.QRect(285, 565, linedit_size_X, linedit_size_Y))
        self.lineEdit_skip_first_points.setObjectName("lineEdit_skip_first_points")
        self.lineEdit_skip_first_points.setText("0")
        self.label_skip_last_points = QtWidgets.QLabel(self.tab_refl_preview)
        self.label_skip_last_points.setFont(font_ee)
        self.label_skip_last_points.setGeometry(QtCore.QRect(325, 565, 80, 16))
        self.label_skip_last_points.setObjectName("label_skip_last_points")
        self.label_skip_last_points.setText("right")
        self.lineEdit_skip_last_points = QtWidgets.QLineEdit(self.tab_refl_preview)
        self.lineEdit_skip_last_points.setFont(font_ee)
        self.lineEdit_skip_last_points.setGeometry(QtCore.QRect(350, 565, linedit_size_X, linedit_size_Y))
        self.lineEdit_skip_last_points.setObjectName("lineEdit_skip_last_points")
        self.lineEdit_skip_last_points.setText("0")
        self.tabWidget_SFM.addTab(self.tab_refl_preview, "")
        self.tabWidget_SFM.setTabText(self.tabWidget_SFM.indexOf(self.tab_refl_preview), "Reflectivity preview")

        # Tab: 2D Map
        self.tab_map = QtWidgets.QWidget()
        self.tab_map.setObjectName("tab_map")
        self.horizontalSlider_scale = QtWidgets.QSlider(self.tab_map)
        self.horizontalSlider_scale.setGeometry(QtCore.QRect(5, 7, 130, 22))
        self.horizontalSlider_scale.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_scale.setObjectName("horizontalSlider_scale")
        self.horizontalSlider_scale.setMinimum(0)
        self.horizontalSlider_scale.setMaximum(1000)
        self.horizontalSlider_scale.setValue(40)
        self.label_polarisation_2d_map = QtWidgets.QLabel(self.tab_map)
        self.label_polarisation_2d_map.setFont(font_ee)
        self.label_polarisation_2d_map.setGeometry(QtCore.QRect(144, 8, 71, 16))
        self.label_polarisation_2d_map.setObjectName("label_polarisation")
        self.label_polarisation_2d_map.setText("Polarisation")
        self.comboBox_polarisation_2d_map = QtWidgets.QComboBox(self.tab_map)
        self.comboBox_polarisation_2d_map.setFont(font_ee)
        self.comboBox_polarisation_2d_map.setGeometry(QtCore.QRect(204, 7, 40, 20))
        self.comboBox_polarisation_2d_map.setObjectName("comboBox_polarisation")
        self.label_axis = QtWidgets.QLabel(self.tab_map)
        self.label_axis.setFont(font_ee)
        self.label_axis.setGeometry(QtCore.QRect(260, 8, 71, 16))
        self.label_axis.setObjectName("label_axis")
        self.label_axis.setText("Axis")
        self.comboBox_axis = QtWidgets.QComboBox(self.tab_map)
        self.comboBox_axis.setFont(font_ee)
        self.comboBox_axis.setGeometry(QtCore.QRect(285, 7, 110, 20))
        self.comboBox_axis.setObjectName("comboBox_axis")
        self.comboBox_axis.addItem("Pixel vs. Point")
        self.graphicsView_map = pg.ImageView(self.tab_map)
        self.graphicsView_map.setGeometry(QtCore.QRect(0, 30, 407, 522))
        self.graphicsView_map.setObjectName("graphicsView_map")
        self.graphicsView_map.ui.menuBtn.hide()
        self.graphicsView_map.ui.roiBtn.hide()
        self.graphicsView_map.ui.histogram.hide()
        colmap = pg.ColorMap(numpy.array([0.0,0.1,1.0]),
                             numpy.array([[0,0,0,255],[255,128,0,255],[255,255,0,255]], dtype=numpy.ubyte))
        self.graphicsView_map.setColorMap(colmap)
        self.pushButton_export_2d_map = QtWidgets.QPushButton(self.tab_map)
        self.pushButton_export_2d_map.setGeometry(QtCore.QRect(300, 555, 100, 25))
        self.pushButton_export_2d_map.setFont(font_ee)
        self.pushButton_export_2d_map.setObjectName("pushButton_export_2d_map")
        self.pushButton_export_2d_map.setText("Export 2D map")

        self.tabWidget_SFM.addTab(self.tab_map, "")
        self.tabWidget_SFM.setTabText(self.tabWidget_SFM.indexOf(self.tab_map), "2D map")

        # StatusBar
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # MenuBar
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuHelp.setTitle("Help")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAlgorithm_info = QtWidgets.QAction(MainWindow)
        self.actionAlgorithm_info.setObjectName("actionAlgorithm_info")
        self.actionAlgorithm_info.setText("Algorithm info")
        self.actionVersion = QtWidgets.QAction(MainWindow)
        self.actionVersion.setObjectName("actionVersion")
        self.menuHelp.addAction(self.actionAlgorithm_info)
        self.menuHelp.addAction(self.actionVersion)
        self.actionVersion.setText("Version 1.3")
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.tabWidget_red_instr_exp.setCurrentIndex(0)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    ##<--